tasks:
- install: null
- ceph:
    cluster: source
    conf:
      source.client.0:
        rgw gc pool: .rgw.gc.0
        rgw log data: true
        rgw log meta: true
        rgw region: zg-2
        rgw region root pool: .rgw.region.0
        rgw user keys pool: .users.0
        rgw user uid pool: .users.uid.0
        rgw zone: z-2
        rgw zone root pool: .rgw.zone.0
- ceph:
    cluster: target
    conf:
      target.client.1:
        rgw gc pool: .rgw.gc.1
        rgw log data: false
        rgw log meta: false
        rgw region: zg-2
        rgw region root pool: .rgw.region.1
        rgw user keys pool: .users.1
        rgw user uid pool: .users.uid.1
        rgw zone: z-1
        rgw zone root pool: .rgw.zone.1
- multisite:
    source.client.0:
      system user:
        access key: 1te6NH5mcdcq0Tc5i8i2
        name: client0-system-user
        secret key: 1y4IOauQoL18Gp2zM7lC1vLmoawgqcYPbYGcWfXv
    target.client.1:
      system user:
        access key: 0te6NH5mcdcq0Tc5i8i2
        name: client1-system-user
        secret key: Oy4IOauQoL18Gp2zM7lC1vLmoawgqcYPbYGcWfXv
    realm: foo
    regions:
      zg-2:
        api name: api1
        is master: true
        master zone: z-2
        zones:
        - z-1
        - z-2
- multisite-rgw-system-test:
        test-name: test_delete_key_versions
        master_client: source.client.0
        master_config:
            cluster_name: source
            user_count: 3
        target_client: target.client.1
        target_config:
            bucket_count: 5
            objects_count: 10
            version_count: 5
            min_file_size: 10
            max_file_size: 20

