# see http://tracker.ceph.com/issues/20360 and http://tracker.ceph.com/issues/18126

tasks:
- install:
    flavor: notcmalloc
- ceph:
- rgw:
    client.0:
      valgrind: [--tool=memcheck, --max-threads=1024]
- swift:
    client.0:
      rgw_server: client.0
