# see http://tracker.ceph.com/issues/20360 and http://tracker.ceph.com/issues/18126

tasks:
- install:
    flavor: notcmalloc
- ceph:
- rgw:
    client.0:
      valgrind: [--tool=memcheck, --max-threads=1024]
- s3tests:
    client.0:
      force-branch: ceph-luminous
      rgw_server: client.0
overrides:
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw lc debug interval: 10
