tasks:
- install:
- ceph:
    log-whitelist:
      - but it is still running
      - 'noup flag(s) set'
      - OSDMAP_FLAGS
      - OSD_OUT_OF_ORDER_FULL
      - CACHE_POOL_NO_HIT_SET
    fs: xfs
- ceph-fuse:
- workunit:
    clients:
      client.0:
        - rbd/test_librbd.sh
    env:
      RBD_FEATURES: "1"
