tasks:
- ssh-keys: null
- ceph-ansible:
      cluster: c1
- ceph-ansible:
      cluster: c2
- install.ship_utilities: null
- new_rgw_multisite:
   realm:
     name: test-realm
     is_default: true
   zonegroups:
     - name: test-zg
       is_master: true
       is_default: true
       zones:
         - name: test-zone
           is_master: true
           is_default: true
           endpoints: [c1.rgw.0, c1.rgw.1]
         - name: test-zone2
           is_default: true
           is_read_only: true
           endpoints: [c2.rgw.1, c2.rgw.0]
- multisite-test.userexec:
      master_client: c1.rgw.0
      test_dir_version: v1
      master_config:
        user_count: 3
- sleep:
   duration: 60
- multisite-test:
      test_client: c1.haproxy.0
      target_config:
        bucket_count: 2
        objects_count: 20
        max_file_size: 10
        min_file_size: 5
      test-name: test_Mbuckets_with_Nobjects
      test_dir_version: v1
- sleep:
   duration: 120
- multisite-test.pull-io-info:
- verify-io:
      verification_script: read_io_info

